version: '3'
services:
  silverstripe:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    env_file:
      - .env.docker
    volumes:
      - .:/var/www/
    tty: true
    links:
      - mariadb

  nginx:
    image: nginx:1.15
    ports:
      - 8080:80
    links:
      - silverstripe
      - mariadb
    volumes:
      - ./dev/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports:
      - 10081:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mariadb

volumes:
  mariadb-volume:
